---
label: Global site config
hide_body: true
is_partial: false
fields:
  - type: text
    name: baseurl
    label: Base URL
    description: Serve the website from the given base URL
    hidden: true
  - type: text
    name: permalink
    label: Permalink
    description: 'The output path for your pages, posts, or collections.'
    hidden: true
    default: '/posts/:slug:output_ext'
  - type: text
    name: title
    label: Title
  - type: text
    name: snipcart_js
    label: Snipcart JavaScript file URL
  - type: text
    name: snipcart_css
    label: Snipcart CSS file URL
  - type: text
    name: snipcart_api_key
    label: Snipcart public API key
  - type: field_group
    name: logos
    label: Logos
    fields:
      - type: field_group
        name: light
        label: Light
        fields:
          - type: file
            name: optimized
            label: Optimized (WEBP or similar)
          - type: file
            name: fallback
            label: Fallback (JPG or PNG)
      - type: field_group
        name: dark
        label: Dark
        fields:
          - type: file
            name: optimized
            label: Optimized (WEBP or similar)
          - type: file
            name: fallback
            label: Fallback (JPG or PNG)
  - type: field_group
    name: styles
    label: Styles config
    fields:
      - type: field_group
        name: backgroundImages
        label: Background images
        fields:
          - type: field_group
            name: primary
            label: Primary
            fields:
              - type: file
                name: optimized
                label: Optimized (WEBP or similar)
              - type: file
                name: fallback
                label: Fallback (JPG or PNG)
          - type: field_group
            name: secondary
            label: Secondary
            fields:
              - type: file
                name: optimized
                label: Optimized (WEBP or similar)
              - type: file
                name: fallback
                label: Fallback (JPG or PNG)
          - type: field_group
            name: product
            label: Product details background
            fields:
              - type: file
                name: optimized
                label: Optimized (WEBP or similar)
              - type: file
                name: fallback
                label: Fallback (JPG or PNG)
      - type: field_group
        name: colors
        label: Colors
        fields:
          - type: text
            name: default
            label: Default light
          - type: text
            name: light
            label: Light
          - type: text
            name: medium
            label: Medium
          - type: text
            name: dark
            label: Dark
          - type: text
            name: active
            label: Active
          - type: text
            name: active_light
            label: Active light
          - type: text
            name: active_medium
            label: Active medium
          - type: text
            name: active_dark
            label: Active dark
          - type: text
            name: dark_grey
            label: Dark grey
          - type: text
            name: light_grey
            label: Light grey
  - type: field_group
    name: sass
    label: Sass
    hidden: true
    fields:
      - type: number
        name: indentWidth
        label: Indent Width
        description: >-
          Used to determine the number of spaces or tabs to be used for
          indentation.
        default: 4
      - type: select
        name: style
        label: Output Style
        description: Determines the output format of the final CSS style.
        default: nested
        config:
          source:
            type: custom
          options:
            - nested
            - expanded
            - compact
            - compressed
      - type: number
        name: precision
        label: Precision
        description: Used to determine how many digits after the decimal will be allowed.
        default: 10
  - type: list
    name: plugins
    label: Plugins
    hidden: true
  - type: list
    name: exclude
    label: Exclude
    description: Exclude directories and/or files from the conversion.
    hidden: true
