---
label: Product
hide_body: false
fields:
- type: text
  name: id
  label: ID
- type: text
  name: title
  label: Title
- type: text
  name: description
  label: Description
- type: text
  name: price
  label: Price
- type: field_group
  name: images
  label: Images
  fields:
  - type: field_group
    name: default
    label: Default
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
  - type: field_group
    name: featured
    label: Featured
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
- type: select
  name: category
  label: Category
  config:
    source:
      type: simple
      section: categories
    options:
    - herbs
    - gifts
    - teas
    - dried goods
- type: boolean
  name: featured
  label: Featured
- type: select
  name: section
  label: Section
  config:
    source:
      type: custom
    options:
    - Store
    - About
    - Home
- type: text
  name: layout
  label: Layout
  hidden: true
  default: product
  config:
    required: true
pages:
- products/lotus-seed.md
- products/huang-qi.md
- products/goji-berry.md
- products/dried-scallops.md
- products/dried-jujube.md
- products/chrysanthemum-tea.md
- products/dang-gui.md
- products/hsu-s-ginseng-tea.md
- products/american-ginseng.md
- products/tea-1.md
- products/eagle-brand-medicated-oil-1-dozen-24ml.md
- products/eagle-brand-medicated-oil-1-dozen.md
- products/sun-s-nest-birds-nest.md
- products/test-dry.md
- products/herbs.md
- products/plant1.md
- products/dried-goods-test.md
- products/313-tea.md
- products/913-tea.md
